name: Run tests and upload coverage

permissions:
  contents: read

on: [push]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false

  go-test:
    name: Run Go tests and collect coverage
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: client/go.mod
          cache: false

      - name: Install Go dependencies
        run: |
          cd client
          go mod download

      - name: Run Go tests with coverage
        run: |
          cd client
          go test -coverprofile=../coverage.txt ./...
    
  node-test:
    name: Run Worker tests and collect coverage
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Set up Node
        uses: actions/setup-node@v6
        
      - name: Install NPM dependencies
        run: npm install

      - name: Run Typescript tests with coverage
        run: npm run coverage

  upload:
    name: Upload results
    runs-on: ubuntu-latest
    needs:
      - go-test
      - node-test
    steps:
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: andrewheberle/serverless-ssh-ca
