name: Release

on:
  release:
    types: [published]

permissions: {}

jobs:
  goreleaser-release:
    name: Build and release with GoReleaser
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      # id-token: write  # Enable for cosign: https://github.com/sigstore/cosign
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: client/go.mod
          cache: false
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
          workdir: client
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload build artifacts
        uses: actions/upload-artifact@v5
        with:
          name: dist-artifact
          path: client/dist/**/*.exe
          retention-days: 7
  msi-release:
    name: Package as an MSI
    runs-on: windows-latest
    permissions:
      contents: write
    needs: goreleaser-release
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: client/go.mod
          cache: false
      - name: Download artifacts
        uses: actions/download-artifact@v6
        with:
          name: dist-artifact
          path: client/dist
      - name: Add WiX Toolset to path
        run: Write-Output $env:WIX | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Install go-msi
        run: go install github.com/mh-cbon/go-msi@latest
      - name: Build MSI
        run: |
          cd client
          go-msi make --arch amd64 --out "$(Join-Path $([System.Environment]::CurrentDirectory) "tmp")" --src ".\templates" --msi ".\dist\ssh-ca-client.msi" --version "$(git describe --tags)"
          Write-Output "$((Get-FileHash -Algorithm SHA256 -Path ".\dist\ssh-ca-client.msi").Hash) ssh-ca-client.msi" | Out-File -FilePath ".\dist\ssh-ca-client.msi.sha256sum"
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            client/dist/ssh-ca-client.msi
            client/dist/ssh-ca-client.msi.sha256sum
